version: v0.13.0

dsn: postgres://kratos:${POSTGRES_PASSWORD}@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://127.0.0.1:4433/
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:8081
        - http://localhost:8081
  admin:
    base_url: http://kratos:4434/
    port: 4434

selfservice:
  default_browser_return_url: http://127.0.0.1:8081/
  allowed_return_urls:
    - http://127.0.0.1:8081

  flows:
    error:
      ui_url: http://127.0.0.1:8081/error
    settings:
      ui_url: http://127.0.0.1:8081/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://127.0.0.1:8081/recovery
    verification:
      enabled: true
      ui_url: http://127.0.0.1:8081/verification
      after:
        default_browser_return_url: http://127.0.0.1:8081/
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:8081/login
    login:
      ui_url: http://127.0.0.1:8081/login
      lifespan: 12h
    registration:
      lifespan: 12h
      ui_url: http://127.0.0.1:8081/registration
      after:
        default_browser_return_url: http://127.0.0.1:8081/

log:
  level: debug
  format: text

secrets:
  cookie:
    - KRATOS_COOKIE_SECRET_PLACEHOLDER
  cipher:
    - KRATOS_CIPHER_SECRET_PLACEHOLDER

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json
