version: v0.13.0

dsn: postgres://kratos:${POSTGRES_PASSWORD}@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://127.0.0.1:4433/
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:3000
  admin:
    base_url: http://kratos:4434/
    port: 4434

selfservice:
  default_browser_return_url: http://127.0.0.1:3000/
  whitelisted_return_urls:
    - http://127.0.0.1:3000

  flows:
    error:
      ui_url: http://127.0.0.1:3000/error
    settings:
      ui_url: http://127.0.0.1:3000/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://127.0.0.1:3000/recovery
    verification:
      enabled: true
      ui_url: http://127.0.0.1:3000/verification
      after:
        default_browser_return_url: http://127.0.0.1:3000/
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:3000/login
    login:
      ui_url: http://127.0.0.1:3000/login
      lifespan: 12h
    registration:
      lifespan: 12h
      ui_url: http://127.0.0.1:3000/registration
      after:
        default_browser_return_url: http://127.0.0.1:3000/

log:
  level: debug
  format: text

secrets:
  cookie:
    - PLEASE_REPLACE_ME_WITH_A_LONG_AND_RANDOM_STRING_SECURELY_GENERATED
  cipher:
    - PLEASE_REPLACE_ME_WITH_A_LONG_AND_RANDOM_STRING_SECURELY_GENERATED

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json
