apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consent
  template:
    metadata:
      labels:
        app: consent
    spec:
      containers:
        - name: consent
          image: oryd/hydra-login-consent-node:v2.3.0
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: HYDRA_ADMIN_URL
              value: "http://hydra-service:4445"
            - name: KRATOS_PUBLIC_URL
              value: "http://kratos-service:4433" # Corrected to kratos-service public port
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0" # Common for development, be cautious in production
            - name: LOG_LEVEL
              value: "debug"
            # Example of other optional vars from the consent app's typical setup:
            # - name: CSRF_COOKIE_NAME
            #   value: "consent_csrf"
            # - name: PORT
            #   value: "3000"
          readinessProbe:
            httpGet:
              path: /health # Common health endpoint for consent app, might need verification
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
