apiVersion: v1
kind: Secret
metadata:
  name: hydra-secrets
type: Opaque
stringData: # Using stringData for easier readability of plain text secrets
  # POSTGRES_PASSWORD is now defined in 'postgres-secrets' Secret.

  # For Hydra's own internal encryption and signing
  HYDRA_SECRETS_SYSTEM: "youReallyNeedToChangeThis" # IMPORTANT: CHANGE THIS

  # For OIDC pairwise subject identifiers
  HYDRA_PAIRWISE_SALT: "youReallyNeedToChangeThisToo" # IMPORTANT: CHANGE THIS
