apiVersion: v1
kind: ConfigMap
metadata:
  name: keto-config
data:
  keto.yml: |
    version: v0.11.0

    serve:
      read:
        port: 4466
      write:
        port: 4467

    # DSN will be configured via environment variable in the Keto deployments
    # dsn: postgres://keto:${POSTGRES_PASSWORD}@postgresd:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4

    # Log level can be set by environment variable in the Keto deployment
    # log:
    #   level: debug
    #   format: text

    # Namespaces can be configured here if needed, or potentially through API/CLI.
    # For now, keeping it as per the original file.
    # Example:
    # namespaces:
    #  - id: 1
    #    name: messages
    namespaces: []
