apiVersion: v1
kind: Secret
metadata:
  name: kratos-secrets
type: Opaque
stringData:
  # POSTGRES_PASSWORD for Kratos DSN will be sourced from the 'postgres-secrets' Secret.
  # No need to define it here again if we are reusing the one from postgres-secrets for the 'kratos' user.
  # If Kratos required a *different* password for its user than the main postgres user,
  # we would define it here, e.g.:
  # KRATOS_USER_PASSWORD: "aDifferentPassword"

  KRATOS_SECRETS_COOKIE: "kratosCookieSecretChangeMe" # IMPORTANT: CHANGE THIS
  KRATOS_SECRETS_CIPHER: "kratosCipherSecretChangeMe" # IMPORTANT: CHANGE THIS
