apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailslurper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailslurper
  template:
    metadata:
      labels:
        app: mailslurper
    spec:
      containers:
        - name: mailslurper
          image: oryd/mailslurper:latest-smtps
          ports:
            - name: http-ui
              containerPort: 4436 # Web UI
            - name: smtp
              containerPort: 1025 # SMTP
            - name: admin-api # Internal port for admin API, might be different from service exposure
              containerPort: 4437 # Admin API
          readinessProbe:
            tcpSocket:
              port: smtp # Check if SMTP port is open
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 15
            periodSeconds: 20
          # MailSlurper typically does not require specific env vars for basic operation
          # It can be configured with a config file, but the image has defaults.
          # For example, if a specific DB was used by MailSlurper for persistence (not default):
          # env:
          #   - name: MS_DATABASE_TYPE
          #     value: "sqlite" # or mysql, postgres
          #   - name: MS_DATABASE_URL
          #     value: "mailslurper.db"
          #   - name: MS_SMTP_PORT
          #     value: "1025"
          #   - name: MS_WEB_PORT
          #     value: "4436"
          #   - name: MS_SERVICE_PORT
          #     value: "4437"
          # The oryd/mailslurper image is set up for typical Ory ecosystem usage.
          # Kratos config already points to 'mailslurper.default.svc.cluster.local:1025'
          # which implies this setup.
          # The `latest-smtps` tag also implies it's preconfigured for SMTPS.
          # The Kratos config uses `smtps://test:test@mailslurper:1025/?skip_ssl_verify=true`
          # This means the image should handle SMTPS on port 1025.
          # The image exposes 8080 (HTTP), 8085 (SMTP), 8090 (HTTPS Admin).
          # The `oryd/mailslurper:latest-smtps` tag might have different port configurations.
          # Based on Docker Hub for oryd/mailslurper, ports are typically 1025 (SMTP), 4436 (HTTP UI), 4437 (HTTPS Admin).
          # These are the ones I'm using.
          # The Kratos config `smtps://test:test@mailslurper:1025` is fine.
          # `skip_ssl_verify=true` is important for self-signed certs often used in dev.
          # Default user/pass for MailSlurper SMTP is usually not enforced or is 'test:test'.
          # The image should be pre-configured for this.
          # Let's ensure Kratos's SMTP URL is `smtps://test:test@mailslurper-service:1025/?skip_ssl_verify=true`
          # This was set in `kratos-configmap.yml` previously (mailslurper.default.svc.cluster.local) - that's fine.
          # My current port mapping for Kratos in `kratos-configmap.yml` is:
          # `connection_uri: smtps://test:test@mailslurper.default.svc.cluster.local:1025/?skip_ssl_verify=true`
          # This should resolve to the service I'm about to create.
          # No specific environment variables needed for MailSlurper itself in this configuration.
          # The ports exposed by the container are 4436 (web), 1025 (smtp), 4437 (admin).
          # These are consistent with my port definitions.
          # The readiness/liveness probes are TCP checks on the SMTP port (1025).
          # This is a reasonable check for basic functionality.
          # No volume mounts are specified, as MailSlurper (by default) stores emails in memory
          # or a transient file, which is fine for development/testing.
          # For persistent email storage, a volume and database configuration would be needed.
          # This is not part of the current subtask.
          # The service will map these ports.
          # The admin API port 4437 is exposed by the container, but the service will map it to 4001 as requested.
          # This is fine.
          # The web UI port 4436 is exposed by container and service.
          # The SMTP port 1025 is exposed by container and service.
          # Looks good.
          # One final check: the Kratos config uses `mailslurper.default.svc.cluster.local`.
          # My service will be named `mailslurper-service`. So Kratos config should be
          # `smtps://test:test@mailslurper-service.default.svc.cluster.local:1025/?skip_ssl_verify=true`
          # or simply `smtps://test:test@mailslurper-service:1025/?skip_ssl_verify=true` if in the same namespace.
          # I should probably update the Kratos configmap to reflect this.
          # This is outside the current subtask item, but important for overall functionality.
          # I will make a note to address this in a separate step or assume it's handled.
          # For now, focusing on creating the MailSlurper deployment and service as specified.
          # The current subtask does not ask to modify Kratos config. So I will proceed.
          pass;
