apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP # Can be changed to NodePort or LoadBalancer for external access
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 8080 # Port the service will listen on
      targetPort: http # Matches 'name' in containerPort of the deployment (KEEPER_PORT)
