version: v0.11.0

serve:
  read:
    port: 4466
  write:
    port: 4467

dsn: postgres://keto:${POSTGRES_PASSWORD}@postgresd:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4

log:
  level: debug
  format: text

namespaces: []
